### PR TITLE
Misc fixes for explosions and radio activation

### LINKED ISSUE #175: Crash when mininuke-ing inside of APC
```
    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x4e) [0x56351eb8b407]
    ./cataclysm-tiles(+0x65552e) [0x56351eb7952e]
    ./cataclysm-tiles(+0x6557c1) [0x56351eb797c1]
    /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f8405d29210]
    ./cataclysm-tiles(_ZNK4item6is_gunEv+0x12) [0x56351ed11696]
    ./cataclysm-tiles(+0xdbf1b1) [0x56351f2e31b1]
    ./cataclysm-tiles(_ZN9visitableI4itemE11visit_itemsERKSt8functionIF13VisitResponsePS0_EE+0x4b) [0x56351f2e768b]
    ./cataclysm-tiles(_ZN4item7processEP6playerRK8tripointbf16temperature_flag+0x135) [0x56351ed213c1]
    ./cataclysm-tiles(+0x9409bd) [0x56351ee649bd]
    ./cataclysm-tiles(_ZN3map24process_items_in_vehicleER7vehicleR6submap+0xc9c) [0x56351ee67888]
    ./cataclysm-tiles(_ZN3map25process_items_in_vehiclesER6submap+0xc1) [0x56351ee67a89]
    ./cataclysm-tiles(_ZN3map13process_itemsEv+0x16d) [0x56351ee71721]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x8ed) [0x56351ec6d81b]
    ./cataclysm-tiles(main+0x12a7) [0x56351e9166e1]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f8405d0a0b3]
    ./cataclysm-tiles(_start+0x2e) [0x56351e997a4e]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    item::is_gun() const
    ??:?
    visit_internal(std::function<VisitResponse (item*, item*)> const&, item*, item*)
    visitable.cpp:?
    visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)
    ??:?
    item::process(player*, tripoint const&, bool, float, temperature_flag)
    ??:?
    process_map_items(item_stack&, safe_reference<item>&, tripoint const&, float, temperature_flag)
    map.cpp:?
    map::process_items_in_vehicle(vehicle&, submap&)
    ??:?
    map::process_items_in_vehicles(submap&)
    ??:?
    map::process_items()
    ??:?
    game::do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?
```

### LINKED ISSUE #1276: radio activation mod problem
1. When using the radio activation mod, the number does not decrease, but increases.
2. The noise emitter is not turned on/off by RC control.
- (Bombs work properly)

The BN version I use is build 2022-01-14-1901-windows .

### PR DESCRIPTION
**Pull request by olanti-p**
#### Purpose of change
1. Fix explosions within vehicles causing segfault (fixes #175)
2. Fix active explosives within monsters not exploding (e.g. when technician pulls an active grenade)
3. Fix radio activation mod having infinite uses 
4. Fix items with `RADIO_ACTIVATION` flag not actually being activated (fixes #1276)
5. Fix active mininuke timer getting reset to 0 on save/load
6. Fix resonance cascade doing nothing
7. Allow RC control to choose which rc car to control, instead of selecting semi-randomly
8. Allow RC control signal to activate items within vehicles or creatures' inventories
9. Allow RC control signal to activate items on all z-levels, remove max range of 30
10. Make radio activation mod easier to craft by allowing more battery variants as components

#### Describe the solution
1. Defer explosions, to avoid modifying data while iterating. This also makes it possible to explode items within monsters inventories. Idea from https://github.com/CleverRaven/Cataclysm-DDA/pull/45693
2. Add code for processing items within monster's inventories
3. Revert item type to TOOL
4. Invoke iuse function if item has `RADIO_ACTIVATION` flag, make `RADIO_INVOKE_PROC` flag set charges of resulting item to 0, so that the next iuse (e.g. explosion) will be invoked when item is processed on next turn.
5. Add arbitrary `max_charges` to the mininuke
6. Fix iterating over area. It seems that the code has not been updated since Whales wrote it, as it still assumes the reality bubble is 3x3 submaps large.
7. Get rid of spaghetti and instead iterate over current z-level looking for items with `RADIO_CONTROLLED` flag
8. Visit all items on map, in vehicles, in monsters and in Characters and check for relevant flags
9. Iterate over all tiles within all active z-levels
10. Add more battery variants as crafting components (cherry-picked from https://github.com/CleverRaven/Cataclysm-DDA/pull/54213)

#### Testing
Mostly for the exact scenarios described in the bugreports and bug descriptions.

#### Additional context
Explosions seem to semi-reliably produce vehicles that have 0 as their cached mass, which results in division by zero and debugmsg informing player of "vehicle with negative drag".

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
You could also look through https://github.com/CleverRaven/Cataclysm-DDA/pull/54213, https://github.com/CleverRaven/Cataclysm-DDA/pull/45661, https://github.com/CleverRaven/Cataclysm-DDA/pull/47066, or https://github.com/CleverRaven/Cataclysm-DDA/pull/47192 to see if there's anything you could salvage.

**Comment by olanti-p** [comment]
> You could also look through ... to see if there's anything you could salvage.

Thanks for the tip!

> [CleverRaven/Cataclysm-DDA#54213](https://github.com/CleverRaven/Cataclysm-DDA/pull/54213)

Cherry-picked crafting changes, the rest I don't think applies.
Unlimited signal reach sounds fun though, I removed max range and z-level restrictions, let's see how it plays out.

> [CleverRaven/Cataclysm-DDA#45661](https://github.com/CleverRaven/Cataclysm-DDA/pull/45661)

Already covered by this PR.

> [CleverRaven/Cataclysm-DDA#47066](https://github.com/CleverRaven/Cataclysm-DDA/pull/47066)

Don't know what to think about this, I kinda like how technicians "swallow" items and force you to kill them.
Out of scope of this PR anyway.

> [CleverRaven/Cataclysm-DDA#47192](https://github.com/CleverRaven/Cataclysm-DDA/pull/47192) 

Also out of scope, but looks neat, will throw on the to-do list.

File: src/explosion.cpp [hunk 1]
```diff
@@ -807,6 +859,37 @@ float blast_radius_from_legacy( int power, float distance_factor )
            ( std::log( 0.75f ) / std::log( distance_factor ) );
 }
 
+explosion_queue &get_explosion_queue()
+{
+    static explosion_queue singleton;
```
Comment (Coolthulhu) [inline src/explosion.cpp:864]: Would be nicer if it was in `game` or some other tracker instead of the anti-pattern thing.
Now, `game` is a god class, but the number of anti-patterns would remain the same instead of being +1'd.

File: src/explosion_queue.h [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+namespace explosion_handler
+{
+
+enum class ExplosionType {
+    Regular,
+    Flashbang,
+    ResonanceCascade,
+    Shockwave
+};
```
Comment (Coolthulhu) [inline src/explosion_queue.h:19]: Not `snake_cased`

File: src/explosion.cpp (hunk 1 above)
Comment (olanti-p) [reply src/explosion.cpp:864]: Yeah, `game` would've been a better place for this, but that haven't crossed my mind back then.

File: src/explosion_queue.h (hunk 2 above)
Comment (olanti-p) [reply src/explosion_queue.h:19]: Argh, I did it again

File: src/monster.cpp [hunk 3]
```diff
@@ -2381,6 +2381,31 @@ bool monster::check_mech_powered() const
...
+            continue;
+        }
+        iter++;
+    }
+
+    process_item_valptr( storage_item, *this );
+    process_item_valptr( armor_item, *this );
+    process_item_valptr( tack_item, *this );
+    process_item_valptr( tied_item, *this );
+}
```
[the remark this answers is not in the document]
Comment (olanti-p) [reply src/monster.cpp:2407]: Item processing can result in item being destroyed. `visit_items` does not allow erasing while visiting, and `remove_items_with` does not allow modifying (processing) items while visiting and optionally erasing.

It'd either require storing item references, and then erasing them in a separate pass while keeping track of erasure order (because `inv` is `std::vector`), or extending `visitable` with a new method and implementing it for all visitable classes, and this PR already felt overbloated.
