### PR TITLE
Don't crash if failed to create texture

### LINKED ISSUE #245: Crash on loading DeadPeople tileset
Got anonymous report.
Windows 7. X32. DirectX9.
Build: 972
Video card: Intel Graphics Media Accelerator (GMA) 3150 

Game crashing on loading DeadPeople TIleset
Ultica tileset does not produce any kind of errors.

he program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: bbd2a5d
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x5a3448[cataclysm-tiles.exe+0x1a3448]), 
    (libbacktrace: _Z21debug_write_backtraceRSo+0xd9@0x5a3448),
    (libbacktrace: 0x5a3448    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x594c59[cataclysm-tiles.exe+0x194c59]), 
    (libbacktrace: log_crash+0x2d7@0x594c59),
    (libbacktrace: 0x594c59    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x594fbb[cataclysm-tiles.exe+0x194fbb]), 
    (libbacktrace: signal_handler+0x52@0x594fbb),
    (libbacktrace: 0x594fbb    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x18c@0x75495e8f[msvcrt.dll+0x65e8f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

### PR DESCRIPTION
**Pull request by olanti-p**
#### Purpose of change
Fixes #245

#### Describe the solution
Replace `assert` with `throw`

#### Testing
Triggered (via debugger) failure when:
1. loading save - game gives `debugmsg` and returns the player to the title screen
2. switching tileset while playing - game shows error popup and falls back to using text mode

### CODE REVIEW

File: src/cata_tiles.cpp [hunk 1]
```diff
@@ -496,7 +504,12 @@ void tileset_loader::load_tileset( const std::string &img_path )
         const SDL_Surface_Ptr &surf_to_use = smaller_surf ? smaller_surf : tile_atlas;
         assert( surf_to_use );
 
-        create_textures_from_tile_atlas( surf_to_use, point( sub_rect.x, sub_rect.y ) );
+        if( !create_textures_from_tile_atlas( surf_to_use, point( sub_rect.x, sub_rect.y ) ) ) {
+            // May happen on some old systems - there's nothing we can do about it
+            throw std::runtime_error(
+                _( "Video error. Try another tileset or a different renderer." )
```
Comment (Coolthulhu) [inline src/cata_tiles.cpp:510]: Double spaces seem to be the norm for player-facing messages.

Comment (anothersimulacrum) [reply src/cata_tiles.cpp:510]: If you're looking for some explanation as to why, it's a standard for monospaced font, which curses has to be and sdl also is.

Comment (Coolthulhu) [reply src/cata_tiles.cpp:510]: At last, I truly see!
