### PR TITLE
Fix possible segfault caused by #2468 when guns are fired

### LINKED ISSUE #2512: Game keeps crashing when trying to fire a turret from vehicle
### Describe the bug

Latest working build for me is [build 2023-03-30-2208](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-03-30-2208) . Since build 2023-03-30-2256 the game keeps crashing with nothing in the logs whenever I try to fire a turret in the vehicle. My guess is: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2468 .

### Steps To Reproduce

1. Enter vehicle
2. Fire turret
3. Game goes kaput

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 42cb8b6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    <color_light_green>Cataclysm++</color> [Cata++],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    PKs Rebalancing [PK_REBALANCE],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Steampunk Mod [steampunk_arcanum],
    UnderrailMetro Mod [underrailmetro_mod],
    <color_light_blue>Really Dark Skies</color> [realdarkskies],
    <color_red>C.R.I.T. Expansion</color> [crt_expansion],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KheirFerrum**
#### Summary

SUMMARY: Bugfixes "Fix possible segfault caused by #2468 when guns are fired."

#### Purpose of change

Fixes #2512 

#2468 has an apparent issue due to how I structured an if block. Fix that ASAP.

Basically, if the gun doesn't use ammo, it will still try to check the amount of ammo passed by the ammo item_location, which will lead to a null reference that crashes the game.

#### Describe the solution

Restructures it so it doesn't route through ammo.get_item()->count() unless the item actually exists.

#### Testing

Fire A7 laser rifle, it doesn't crash.

#### Additional context

I'm an idiot and I should've playtested this a lot fucking more.

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
image

spawned UPS and A7 laser rifle, they fire without segfault. i'll review rest of the code after.

File: src/ranged.cpp [hunk 1]
```diff
@@ -841,10 +841,9 @@ int ranged::fire_gun( Character &who, const tripoint &target, int max_shots, ite
 
     int shots = max_shots;
     // Number of shots to fire is limited by the amount of remaining ammo
-    if( gun.ammo_required() && !ammo ) {
-        shots = std::min( shots, static_cast<int>( gun.ammo_remaining() / gun.ammo_required() ) );
-    } else {
-        shots = std::min( shots, ammo.get_item()->count() / gun.ammo_required() );
+    if( gun.ammo_required() ) {
+        shots = std::min( shots, ( !ammo ? gun.ammo_remaining() : ammo.get_item()->count() ) /
+                          gun.ammo_required() );
```
Comment (scarf005) [inline src/ranged.cpp:846]:
```suggestion
        const int ammo_left = ammo ? ammo.get_item()->count() : gun.ammo_remaining();
        shots = std::min( shots, ammo_left / gun.ammo_required() );
```
i think introducing a temporary variable would improve readability here.
