### PR TITLE
Fix several prying/picking tools bugs

### LINKED ISSUE #1923: Examine auto-lockpick action asks for a direction
### Describe the bug

Examining a pickable object says "you attempt to pick lock", then asks for a direction instead of picking the examined object.

All iuse functions have a position argument and one is supplied to `pick_lock_actor::use`, but the function doesn't use it and unconditionally asks for direction instead.

### Steps To Reproduce

* Spawn a locked safe
* Spawn a lockpick
* Pick the lockpick up (wielding OK)
* Examine the safe
* Direction prompt appears

### Expected behavior

No direction prompt, examining the safe already required providing a direction.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 68d3ee02ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Magiclysm [magiclysm],
    Manual Bionic Installation [manualbionicinstall]
]

### Additional context

_No response_

### LINKED ISSUE #2130: Prying tools unusable when holstered, manholes and coffins unselectable in examine
### Describe the bug

The following weird behaviors have been observed:
1. Prying tools are unusable if stored in tool belts or other holster items.
2. Sealed coffins and covered manholes do not even show as being selectable when `e`xamining them, regardless of where your prying tool is, requiring you to manually `a`activate it or use the `%` menu.

### Steps To Reproduce

1. Spawn in a crowbar, put it in a toolbelt.
2. Place a sealed crate and a locked door.
3. Observe that the crate and door can't be pried.
4. Activate tool belt to remove the crowbar, prying the crate and door now works on `e`xamine.
5. Spawn in a sealed coffin and a manhole.
6. Observe neither of those are even shown as selectable in `e`xamine, but hitting `A` with your wielded crowbar works.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 7bab7c6 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Elevated bridges [elevated_bridges],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Simplified Nutrition [novitamins]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoCottret**
#### Summary
SUMMARY: Bugfixes "Fix several prying/picking tools bugs"

#### Purpose of change
Fixes #2130 
- manholes and coffins were missing a json field
- when checking for the best items with lockpick/prying qualities, wearable items weren't taken into account

Fixes #1923 
- basically what is in the issue, the parameter was passed to the function but never used

##### 2130
- add the missing json field so that they can be pried open with examine
- remove the check on wearable item
  - you can directly lockpick a lockpickable thing with a worn hairpin
  - you can also pry a pryable thing with crowbar in a toolbelt

##### 1923
- make the function ask for a direction only if the parameter passed isn't valid

#### Testing
- worn item: hairpin (action and examine key)
  - sealed coffin: no
  - crate: no
  - man hole: no
  - locked wood door: yes
  - gun safe: yes
- worn item: toolbelt with crowbar (examine only)
  - sealed coffin: yes
  - crate: yes
  - man hole: yes
  - locked wood door: yes
  - gun safe: no
- crowbar (action and examine key)
  - sealed coffin: yes
  - crate: yes
  - man hole: yes
  - locked wood door: yes
  - gun safe: no

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -1462,13 +1462,10 @@ void iexamine::gunsafe_el( player &p, const tripoint &examp )
...
-        // Don't search for worn items such as hairpins
-        if( p.get_item_position( &it ) >= -1 ) {
-            item temporary_item( it.type );
-            return temporary_item.has_quality( quality_id( "PRY" ), 1 );
-        }
-        return false;
+    std::vector<item *> prying_items = p.items_with( []( const item & it ) {
+        // we want to get worn items (eg crowbar in toolbelt), so no check on item position
+        item temporary_item( it.type );
+        return temporary_item.has_quality( quality_id( "PRY" ), 1 );
```
Comment (Coolthulhu) [inline src/iexamine.cpp:1468]: This temporary item hack shouldn't be needed. Just `it.has_quality` should work.
