### PR TITLE
fix: empty underslung gun doesnt prevent going into firing mode UI

### LINKED ISSUE #3966: Underslung guns disable their main weapon when they run out of ammo
### Describe the bug

If you have an underslung gun and fire until it is out of ammo, you will not be able to switch fire modes back to your main weapon until you either remove the mod or insert ammo back into your underslung weapon.

### Steps To Reproduce

1. Attach underslung weapon (say shotgun) to your main gun with ammo. You can also skip this step and step 2 by attaching an empty weapon.
2. Switch fire modes to the underslung weapon and fire until out of ammo
3. Get errors about being out of ammo when you press 'f', which stops you from changing fire modes

### Screenshots

Underslung

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 428d071 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    BioCo Content [bioco],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Garden Pots [growable-pots],
    Gourmand's Graces [Gourmand'sGraces],
    Makeshift Items Mod [makeshift],
    More Makeshift Stuff [makeshift_stuff],
    Wild Living [WildLiving],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Even More Mutations [even_more_mutations],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    Thog's Things [Thogs_Things],
    Thog's Vehicles [Thogs_Vehicles],
    THRESHOLD [add_mutant],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Urban Development [Urban_Development],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Shrub it off [shrub_mod],
    Aftershock - Easydocs [AFS_Easydocs],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Targeted Mutations [TaMu]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ekaratzas**
Without this fix having an empty underbarrel mod/gun like the grenade launcher prevents the player from activating the firing ui via 'f'. This is especially troublesome as most players, including myself, only know how to change firing modes via this UI. This effectively prevents players from switching firing mode to the main weapon.

## Purpose of change

This change allows the player to activate firing mode UI via 'f' in the case where the underslung gun/mod is out of ammo but the main gun still has ammo. This is especially confusing for most players as they are used to changing firing modes from this UI only.

Fixes #3966 

## Describe the solution

Solution simply checks if any of the gun modes of the current weapon ca be fired at the moment, not just the 'currently selected one'.

## Testing

Spawn character with m4 carbine and m320 grenade launcher. Attach them together. switch to GLM and shoot it once. See that 'f' can still activate firing UI and you can switch firing modes from there and keep shooting the main gun.

firing_mode_empty_glm

### CODE REVIEW

**Review by chaosvolt — DISMISSED** [review]

File: src/avatar_action.cpp [hunk 1]
```diff
@@ -675,12 +675,13 @@ bool avatar_action::can_fire_weapon( avatar &you, const map &m, const item &weap
...
-    const gun_mode &mode = weapon.gun_current_mode();
-    bool check_common = ranged::gunmode_checks_common( you, m, messages, mode );
-    bool check_weapon = ranged::gunmode_checks_weapon( you, m, messages, mode );
-    bool can_use_mode = check_common && check_weapon;
-    if( can_use_mode ) {
-        return true;
+    for( const std::pair<const gun_mode_id, gun_mode> &mode_map : weapon.gun_all_modes() ) {
+        bool check_common = ranged::gunmode_checks_common( you, m, messages, mode_map.second );
+        bool check_weapon = ranged::gunmode_checks_weapon( you, m, messages, mode_map.second );
+        bool can_use_mode = check_common && check_weapon;
```
Comment (scarf005) [inline src/avatar_action.cpp:681]:
```suggestion
    for( const std::pair<const gun_mode_id, gun_mode> &mode_map : weapon.gun_all_modes() ) {
        const bool check_common = ranged::gunmode_checks_common( you, m, messages, mode_map.second );
        const bool check_weapon = ranged::gunmode_checks_weapon( you, m, messages, mode_map.second );
        const bool can_use_mode = check_common && check_weapon;
```

**Review by scarf005 — CHANGES_REQUESTED** [review]

**Review by scarf005 — APPROVED** [review]
