### PR TITLE
Fix CTD when trying to drop worn NO_TAKEOFF items, other related fixes

### LINKED ISSUE #1475: Dropping items with NO_TAKEOFF via item summary menu, possibly others, causes crash
# Describe the bug

Normally trying to drop an item that can't be taken off, such as the active foodperson mask, simply fails and reminds you it can't be taken off. But if you go into the inventory menu with `i`, select the offending item, then hit `d`rop from there, the game promptly crashes.

It correctly recognizes you can't take it off in the `d`, `D`, and `T` menus, won't let you `t`hrow it either, and correctly fails to unequip if you try it in the `+` sort armor menu. Also fails if you try to move it in the AIM `/` menu.

# Steps To Reproduce

1. Spawn in a foodperson mask.
2. Turn it on.
3. Enter inventory with `i`, select the mask.
4. Select `d` to drop.
5. Crash.

# Expected behavior

Same failure message as in all other contexts.

# Screenshots

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 205c22b [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda]
]
```

# Additional context

This is basically just the `NO_TAKEOFF` version of the earlier https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1074 I found except with crashing instead of successfully dropping the undroppable.

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Bugfixes "Fixed CTD when trying to drop worn NO_TAKEOFF items, other related fixes"

#### Purpose of change
Fix #1475, improve NO_TAKEOFF handling in some other cases

#### Describe the solution
1. In dropping activity, show debugmsg and skip item if failed to drop it
2. Add message when failing to drop the item through item overview screen (`i`->select item->`Enter`)
3. Don't show worn NO_TAKEOFF items in multidrop menu
4. In item overview screen, fix colors of drop & wield options for worn NO_TAKEOFF items
5. In AIM, check whether can drop item before starting activity

#### Testing
Tried to drop active worn foodperson mask via multidrop screen, AIM and via item overview screen, all failed.

### CODE REVIEW

File: src/advanced_inv.cpp [hunk 1]
```diff
@@ -870,6 +870,10 @@ bool advanced_inventory::move_all_items( bool nested_call )
             for( size_t idx = 0; idx < g->u.worn.size(); ++idx, ++iter ) {
                 item &it = *iter;
 
+                if( !g->u.can_takeoff( it ).success() ) {
```
Comment (Coolthulhu) [inline src/advanced_inv.cpp:873]: `get_avatar()` preferred.

**Comment by Coolthulhu** [comment]
Would be nice if the menu still showed the undroppable items, just grayed them out.

I found an incredibly tiny exploit: foodperson mask can be reloaded with any viable battery, including empty. Empty batteries will break the "curse" quickly.

**Comment by chaosvolt** [comment]
> I found an incredibly tiny exploit: foodperson mask can be reloaded with any viable battery, including empty. Empty batteries will break the "curse" quickly.

Easy fix should be tacking on NO_RELOAD (and NO_UNLOAD if not present) to the active version, unless reloading of magazine-fed items is borked.

**Comment by Treah** [comment]
This seams to not be fixed for non wear items when moving still. I just built a newly pulled version of the game and still am getting the error "You are not wearing that item" when trying to put an item right below me which is not a container or a shelf. 
image
