### PR TITLE
Fix burnt mycus ground burning road

### LINKED ISSUE #1882: Burning mycus ground will burn off the road
### Describe the bug

As title says, when lighting mycus ground on fire, it will make road tiles disappear when the fire burns out and a dirt tile replaces it. Roads have a concrete layer under asphalt.

### Steps To Reproduce

1. Spawn a fungaloid close to the road.
2. Wait for the mycus ground to appear on the road.
3. Light it on fire.
4. Wait.

### Expected behavior

I would expect concrete tiles or road (pavement) to be still there when fire burns out.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2937745 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Lighter vehicle parts [lighter_vehicle_parts],
    no ups mp3 [no_UPS_mp3],
    MSX Fake Snow [UDP_BN_FAKE_SNOW]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoCottret**
#### Summary
SUMMARY: Bugfixes "Fix burnt mycus ground burning road"

#### Purpose of change
Fixes #1882 but it pushes the change further.
Mycus spread was always kind of a nightmare. It made entire zones a no go, adding a ton of lag etc.
Well I won't detail this part, you know what I mean. A lot of people just use a mod to remove it, so in the end, is this a fun feature?

#### Describe the solution
With this change they can still be a pain, but only on terrains like dirt, grass, trees etc.
So they will now mostly take over part of the wild.

#### Describe alternatives you've considered
Allowing it to convert wood.
I think it makes sense, but would require some changes to wood terrains.

#### Testing

After 2 hours wait this is the conversion result:
image

From top to bottom
- 1st row: dirt, grass etc. -> converted
- 2nd row: tree, bushes etc. -> converted
- 3rd row: wood stuff -> not converted
- 4th row: metal, pavement etc. -> not converted

#### Additional context
Keeping in mind that the conversion system could be extended to more terrains again, but only if when we find a way to make the mycus more "fun".

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Clang-tidy complains about:
```
 /home/runner/work/Cataclysm-BN/Cataclysm-BN/src/fungal_effects.cpp:48:1: error: Variable 'flag_FLAMMABLE' declared but not used. [cata-unused-statics,-warnings-as-errors]
static const std::string flag_FLAMMABLE( "FLAMMABLE" );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Cataclysm-BN/Cataclysm-BN/src/fungal_effects.cpp:49:1: error: Variable 'flag_FLAT' declared but not used. [cata-unused-statics,-warnings-as-errors]
static const std::string flag_FLAT( "FLAT" );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Cataclysm-BN/Cataclysm-BN/src/fungal_effects.cpp:57:1: error: Variable 'flag_WALL' declared but not used. [cata-unused-statics,-warnings-as-errors]
static const std::string flag_WALL( "WALL" );
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

File: src/fungal_effects.cpp [hunk 1]
```diff
@@ -207,11 +187,6 @@ void fungal_effects::spread_fungus_one_tile( const tripoint &p, const int growth
             }
             converted = true;
         }
-    } else if( m.has_flag( flag_WALL, p ) && m.has_flag( flag_FLAMMABLE, p ) ) {
-        if( x_in_y( growth * 10, 5000 ) ) {
-            m.ter_set( p, t_fungus_wall );
-            converted = true;
-        }
```
Comment (Coolthulhu) [inline src/fungal_effects.cpp:214]: Destroying flammable walls is fine. It's not the same thing as fungus wrecking otherwise tough roads or anything, it makes sense.

Comment (leoCottret) [reply src/fungal_effects.cpp:214]: Alright, it does include painted walls but it turned out they can only be made from a wood wall
