### PR TITLE
Optimize electric grid

### LINKED ISSUE #1322: strange lags in specific place
# Describe the bug
Strange game lags during movent. It happens only in specific place in my save (pool and southern house). Other places are ok. Save attached. 
I am unsure if it my save problem or some game bug. Feell free to close this if not bug. Thanks

# Steps To Reproduce

1. Load my save (sherry/misato)
2. Hold move button. Left or right for example. After moving about ten tiles game freezes for small time. Look like some heavy calculation happens. 
This happens only if I move near pool/house south of the pool.

# Expected behavior

Normal movement as in other places (without periodic lags).

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0a8096c [64-bit]
- Graphics Version: Tiles
- Game Language:  [Russian]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Aftershock [aftershock],
    No Filthy Clothing [no_filthy_clothing],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]
[save.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8018240/save.zip)

### PR DESCRIPTION
**Pull request by SaintCirno9**
#### Summary

SUMMARY: [Performance] "Optimize electric grid"

#### Purpose of change

To fix #1322 

#### Describe the solution

The profiler result in #1322 is rather inaccurate because of the compile options we use, I guess. 
In fact, the major performance eater in `electric_grid_at` is the copy of the `tripoint_abs_omt`, which is weird.
Simply using a reference there solves the lag.

#### Testing

Load the save attached in #1322 , then walk around.

- Before this PR
before

- After this PR
after

#### Additional context

I also made the `distribution_grid_tracker::on_saved()` only reload needed things, but the improvement is not as significant as the reference used in `electric_grid_at`.

### CODE REVIEW

File: src/overmapbuffer.cpp [hunk 1]
```diff
@@ -1686,7 +1686,8 @@ std::set<tripoint_abs_omt> overmapbuffer::electric_grid_at( const tripoint_abs_o
     open.emplace( p );
 
     while( !open.empty() ) {
-        const tripoint_abs_omt elem = open.front();
+        // It's weired that the game takes a lot of time to copy a tripoint_abs_omt, so use reference here.
+        const tripoint_abs_omt &elem = open.front();
         open.pop();
```
Comment (Coolthulhu) [inline src/overmapbuffer.cpp:1691]: Undefined behavior alert.
`pop` alters `front` and using them this way can cause a crash.
`elem` should only be used until `open` changes in any way. From what I can tell, putting the `pop` below `omc` definition below should do the job.

Comment (SaintCirno9) [reply src/overmapbuffer.cpp:1691]: Well, I do know that it may cause some memory problem, but my play through seems fine, so after simple test, I just ignore that. 
I think it will be better to put the pop() at the end of the while loop, since a queue is a FIFO struct.

Comment (Coolthulhu) [reply src/overmapbuffer.cpp]: > Well, I do know that it may cause some memory problem, but my play through seems fine, so after simple test, I just ignore that.

You shouldn't ignore problems like that. At least leave a comment when ignoring, so that if things break, we know where to look.
Otherwise if it did start breaking, we'd probably need to spend a lot of time tracking it down.
There are many different platforms, so manual testing can't be relied on.
