### PR TITLE
fix: negative values in armor calculations

### LINKED ISSUE #4300: negative armor resistances on windows mxe build
### Describe the bug

After the `2024-03-03` update that fixed the Fire/Acid resistances, it made a nasty side effect of giving certain items negative resistances. Seems to be mainly with watches, but I don't know which other items are affected by this.

### Steps To Reproduce

1. Open Game.
2. Find a Watch (Smart Watch and Diver's Watch is what I've seen)
3. Be amazed that you are over negative 2 billion vulnerable to all the main resistances except Fire and Acid.

### Screenshots

Resistance

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 8bb6364 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vitalyo7**
## Purpose of change

Fixes #4300

Checked the code against CDDA to see if they handle calculations differently or how they handle this particular issue. They do not have this calculation and it appears to be a BN specific calc only.

Compared the builds in MSYS and Visual Studio to confirm the issue is related to divide by zero and not some other factor.

Tested in MSYS, by running a game, spawning a watch via debug and not seeing negative numbers.

Not needed, reviewing the code should be enough to verify that divide by zero should now be properly handled.

N/A

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -6188,7 +6188,9 @@ static int phys_resist( const item &it, damage_type dt, clothing_mod_type cmt,
             base_resistance = iter->second;
         }
 
-        float damaged_resistance = base_resistance * eff_thickness / it.get_thickness();
+        // We can have 0 thickness items, so need to check for it to ensure we don't get NaN in calcs
+        int thickness = it.get_thickness();
+        float damaged_resistance = ( 0 != thickness ) ? base_resistance * eff_thickness / thickness : 0.0f;
```
Comment (scarf005) [inline src/item.cpp:6193]:
```suggestion
        const int thickness = it.get_thickness();
        const float damaged_resistance = ( thickness == 0 ) ? 0.0f : base_resistance * eff_thickness / thickness;
```

1. adding `const` improves readability by removing moving/mutable parts in code.
2. (optional) it might be a good idea to use `variable != 0` over `0 != variable` as variables are usually more important than numbers.
3. (optional) it also might be a good idea to prefer `==` over `!=` as it may reduces cognitive load by one (is _not_ something -> is something)

**Review by scarf005 — APPROVED** [review]

**Review by chaosvolt — APPROVED** [review]
