### PR TITLE
fix: filling containers from the map

### LINKED ISSUE #3556: Refilling containers at water source only fills 2 units at a time.
### Describe the bug

Using a water source should fully fill a container.
Refilling containers from a water source only fills 2 units at a time.

### Steps To Reproduce

1. Interact with water source.
2. Select fill container.
3. Observe container having 2 units out of x filled.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 497c99f [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Stats Through Kills [stats_through_kills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joveeater**
## Summary
SUMMARY: Bugfixes "Fix filling containers from maps ending early"

## Purpose of change

Fixes #3556.

## Describe the solution

Backwards conditional was causing it to end early.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -1512,7 +1512,7 @@ void activity_handlers::fill_liquid_do_turn( player_activity *act, player *p )
                     charges = std::max( 1, source->charges_per_volume( volume_per_second ) );
                     source->charges = charges;
                     source = cb( std::move( source ) );
-                    return !( source && source->charges != charges );
+                    return !( !source || source->charges != charges );
```
Comment (scarf005) [inline src/activity_handlers.cpp:1515]:
```suggestion
                    return source && source->charges == charges;
```

I think this expression could be simplified.

[context](https://chat.openai.com/share/0f8e0b3d-7af8-40aa-9760-983444ebc120)

**Review by scarf005 — CHANGES_REQUESTED** [review]

**Review by scarf005 — APPROVED** [review]
