### PR TITLE
fix floor destroyed message prompt when bashing on stairs

### LINKED ISSUE #1771: Bashing while standing on down stairs causes "Floor below is destroyed" event every time
### Describe the bug

Upper part of the stairs doesn't count as floor or support, but the bash function checks for floor or support after bashing, to catch cases where player bashes down the floor they're standing on.
It notices lack of support, so it triggers "where do you want to fall?" prompt, but choosing to fall does nothing.

### Steps To Reproduce

1. Find stairs and climb up
2. Bash a wall or furniture while standing on down stairs (that is, upper part of the stairs)
3. "Floor was destroyed"

### Expected behavior

No message unless the player actually ends up destroying the stairs that support them.

### Screenshots

_No response_

### Versions and configuration

Not system dependent.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoCottret**
#### Summary
SUMMARY: Bugfixes "fix floor destroyed message prompt when bashing on stairs"

#### Purpose of change
Fixes #1771 
To give more details, when something is bashed, the game checks if there is a "floor or support" below the player to know if it should prompt the "Floor destroyed" message.
To do that, it calls the has_floor_or_support function, that checks wether the player can go below or not. It doesn't make the difference between open air or stairs and similar terrains that allows you to go below.

#### Describe the solution
Now, it also checks if the terrain has a "GOES_DOWN" flag, and won't prompt the message if it has.

#### Describe alternatives you've considered
I hesitated on editing has_floor_or_support, but since it's used several times in different context it could have side effects.

#### Testing
Create a stair, go up, spawn a furniture next to it, bash it, no more message.

### CODE REVIEW

File: src/handle_action.cpp [hunk 1]
```diff
@@ -806,7 +806,7 @@ static void smash()
             }
         }
 
-        if( !here.has_floor_or_support( u.pos() ) ) {
+        if( !here.has_floor_or_support( u.pos() ) && !here.has_flag_ter( "GOES_DOWN", u.pos() ) ) {
```
Comment (Coolthulhu) [inline src/handle_action.cpp:809]: Terrain flags have a pseudo-int-id feature for faster checks and a tiny bit more type safety. For `"GOES_DOWN"`, there's a `TFLAG_GOES_DOWN` pseudo-int-id.
