### PR TITLE
Fix items with NO_UNWIELD being droppable via inventory item menu

### LINKED ISSUE #1074: NO_UNWIELD doesn't work from inside item menu
# Describe the bug

Items with `NO_UNWIELD`, like bionic weapons or the mech lasers, can be dropped via examining them in inventory and hitting `d`.

The `w` key in the same screen correctly stops with the message that you can't unwield it, and it does not show up in the `d` or `D` menu, nor does it drop them if you try to trick it via hitting the item's key in said menus.

# Steps To Reproduce

1. Start game as a profession that starts with a weapon bionic such as bionic assassin.
2. Activate your monomolecular blade or otherwise end up wielding a `NO_UNWIELD` weapon.
3. Open your inventory with `i`.
4. Select the wielded weapon.
5. Hit `d`.

# Expected behavior

Un-unwieldable weapons to stay firmly attached when eyeballed in the item screen.

# Screenshots

image

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: dd8ef4b [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Simplified Nutrition [novitamins]
]
```

# Additional context

https://www.youtube.com/watch?v=rPIylUlXZxE

### PR DESCRIPTION
**Pull request by ThinkInvis**
#### Summary

SUMMARY: [Bugfixes] "Prevent using inventory item menu to drop items with the NO_UNWIELD flag; correct related hint colors"

#### Purpose of change

Fixes #1074. From the look of things, schizophrenia could also cause this issue; this should be fixed as well.

Also corrects the hint colors of relevant actions in the IIM (drop, wield, throw): previously, *all* items would hint as undroppable if the wielded item had NO_UNWIELD. Also, items with NO_UNWIELD would incorrectly hint as throwable and (un)wieldable; and items would hint as wieldable while a NO_UNWIELD item was wielded.

#### Describe the solution

Intercepts dropping in `Character::drop(item_location loc, const tripoint & where)`, a method used only by `game::inventory_item_menu` (IIM), `player::takeoff` ('take off' action), and `Character::suffer_from_schizophrenia` (schizophrenia effects). The purpose of this method appears to be to drop only a single item. New code is based on a check in `game::wield`.

Adjusted hint colors in `game::inventory_item_menu` as follows:
- Wield: always green --> grey if the current wielded item is NO_UNWIELD, green otherwise
- Throw: always green --> grey if the current wielded item is NO_UNWIELD *and* is the item being considered for throwing, green otherwise
- Drop: grey if the current wielded item is NO_UNWIELD, green otherwise --> grey if the current wielded item is NO_UNWIELD *and* is the item being considered for dropping, green otherwise

#### Describe alternatives you've considered

There may be other places to intercept dropping for this purpose. This may also be an unsafe place/way to do so (can NPCs trigger the message and maybe cause incorrect wording? was unsure how to test this); however, I haven't been able to find any such issues yet.

Adjusting hint colors may be more suitable for another PR, but I figured it was closely related enough to count. Set up as 2 separate commits just in case it wasn't.

##### Reproduction
1. Launched a release x64 build of bee8a49, with data/font/Terminus.ttf deleted due to a rendering bug in vcpkg.
2. Started a new game using Play Now! (Fixed Scenario).
3. Spawned in and wielded an extended toolset item.
4. Opened the inventory item menu for the extended toolset, and observed that drop hinted correctly as impossible/grey, but that wield and throw both incorrectly hinted as possible/green.
5. Opened the inventory item menu for another item (a cellphone), and observed that drop hinted incorrectly as grey, that wield hinted incorrectly as green, and that throw hinted correctly as green.
6. Opened the inventory item menu for the extended toolset, pressed the drop key, and observed that the toolset was dropped as with a normal item, despite hint color and item flags to the contrary.
##### Fix verification
7. Closed the previous game instance and launched a release x64 build of bee8a49 + this PR.
8. Started a new game using Play Now! (Fixed Scenario).
9. Spawned in and wielded an extended toolset item.
10. Opened the inventory item menu for the extended toolset, and observed that drop, wield, and throw all hinted correctly as grey.
11. Opened the inventory item menu for another item (a smartphone), and observed that wield hinted correctly as grey, and that drop and throw hinted correctly as green.
12. Opened the inventory item menu for the extended toolset, pressed the drop key, and observed that the toolset was not dropped ("You cannot unwield your extended toolset.").
##### Regression checks
13. Verified that all other combinations of IIM actions and NO_UNWIELD states worked as expected, matching both hint color and resultant action:
    - No NO_UNWIELD items, target item is not wielded --> IIM can drop, wield, and throw
    - No NO_UNWIELD items, target item is wielded --> IIM can drop, (un)wield, and throw
    - NO_UNWIELD item available but unwielded, target item is not wielded --> IIM can drop, wield, and throw
    - NO_UNWIELD item available but unwielded, target item is wielded --> IIM can drop, (un)wield, and throw
    - NO_UNWIELD item wielded, target item is not wielded --> IIM can drop and throw, but not wield
    - NO_UNWIELD item wielded, target item is wielded --> IIM cannot drop, throw, or (un)wield

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -2487,6 +2487,16 @@ std::list<item *> Character::get_dependent_worn_items( const item &it )
 
 void Character::drop( item_location loc, const tripoint &where )
 {
+    item &oThisItem = *loc;
```
Comment (Coolthulhu) [inline src/character.cpp:2490]: Naming style: `oThisItem` is systems Hungarian plus camelCase, while most of the new code uses `snake_case` and names without systems Hungarian noise.
