### PR TITLE
fix: multiple vehicle faucets no longer multiply supposedly-available crafting materials

### LINKED ISSUE #3885: Vehicle tanks claim to have twice as much liquid for crafting as actually available
### Describe the bug

Crafting from vehicle tanks claims there is twice as much liquid available as it should. If you attempt to craft more than what you actually have in the tank, it will error and halt your in-progress craft.
```
 DEBUG    : Attempted a recipe with no available components!

 FUNCTION : select_item_component
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\crafting.cpp
 LINE     : 1460
 VERSION  : BN daf4002
```

### Steps To Reproduce

1. Spawn in a vehicle with a tank and a faucet installed on it.
2. Fill that tank with a plastic bottle of water.
3. Start to craft clean water, notice that it says you have 4 units avilable, not the 2 you put in the tank.
4. Craft 2 units of clean water, tank empties as expected.
5. Refill the tank with another bottle of water, this time try to make 4 clean water.
6. Observe it bug out.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: daf4002 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Elevated bridges [elevated_bridges],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Mining Mod [Mining_Mod],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by karxi**
### Required
- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) so it can be closed automatically.
- [x] I have [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

## Purpose of change
- fixes #3885

Bugfixing! Multiple faucets (and things that act like faucets, such as the kitchen vehicle part(s)) in a vehicle will, when all within crafting range, *each* report the vehicle's entire quantity of various liquids available...meaning you can get told that you have 2×, 3×, 4×, or more of whatever you need to make something.
Obviously suboptimal.

## Describe the solution
Made inventory::form_from_map keep a mapping of vehicles and their relevant parts that it has checked (and accepted as providing features), and made each successful vpart_reference check add to the set of parts for that vehicle.

## Describe alternatives you've considered
Crying quietly.

## Testing
Make or find a vehicle with a liquid used to craft; check the crafting menu to see the expected amount of fluid there is to work with; add 2+ water faucets; watch as the found (available) crafting mats don't multiply.

## Additional context
This should also head off some potential issues with vehicle_part features, but those weren't my priority and that system could use updating anyway.

### CODE REVIEW

File: src/inventory.cpp [hunk 1]
```diff
@@ -576,6 +577,12 @@ void inventory::form_from_map( map &m, std::vector<tripoint> pts, const Characte
             continue;
         }
         vehicle *const veh = &vp->vehicle();
+        if( auto ovi = checked_vehi.find( veh ); ovi == checked_vehi.end() ) {
```
Comment (scarf005) [inline src/inventory.cpp:580]:
```suggestion
        if( auto ovi = checked_vehi.find( veh ); ovi == checked_vehi.end() ) {
```
let's use https://en.cppreference.com/w/cpp/container/unordered_map/contains

Comment (karxi) [reply src/inventory.cpp:580]: Those suggestions don't seem to differ at all?

Comment (scarf005) [reply src/inventory.cpp:580]: fixed

**Review by chaosvolt — DISMISSED** [review]
1. Compiled and load-tested.
2. Spawned in an RV.
3. Checked crafting menu, says I've got 242 units of water available.
4. Used debug hammerspace to install the back with wall-to-wall kitchen units.
5. Removed debug hammerspace, checked crafting menu, still only shows 242 units of water available.
6. Spawned in a fuckload of dried rice and made a bunch of cooked rice, the error message never showed up.

image

**Review by chaosvolt — APPROVED** [review]
