### PR TITLE
Fix dogs ignoring leash when they see enemies

### LINKED ISSUE #1997: Leashed dogs ignore the leash when they see enemy
### Describe the bug

Leashed dogs ignore the leash when they see an enemy.

### Steps To Reproduce

1. Obtain a short rope and a friendly dog
2. Add the leash to the dog, start leading it
3. Spawn a zombie 20 tiles away
4. The dog runs away to attack

### Expected behavior

The dog stays on the leash

### Screenshots

_No response_

### Versions and configuration

Game version 6b7f879b

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoCottret**
#### Summary
Fix #1997 
SUMMARY: Bugfixes "Fix dog ignoring leash when they see enemies"

#### Purpose of change
1) Creatures would ignore leashes when they want to attack (or possibly flee from) a target.
2) A dog has a probability to bark at a monster, which remove a whooping 100 move points. This means that given enough monsters, a dog would "bark itself to death", being unable to follow the player even leashed because it used all its move points to bark every turn.

#### Describe the solution
1)
- If the leashed animal is already close to the player and a hostile creature is adjacent to the player, try to attack it to defend the player. I also increased the leash range a bit to allow dogs to do their hit and run attacks (long leashes do exist)
- Otherwise stay close to the player
2)
- Reduce the barking cost from 100 to 10. Having your dog unable to move because he's too busy barking at zombies is kind of stupid. And dogs can bark while moving.

#### Describe alternatives you've considered
Solution "2)" could buff mi-go (and monsters that use parrot), so I could add a check on leashed monsters/PET/something if needed. But I find it weird that they need to stop attacking/moving to basically just talk.

#### Testing
Tested with several dogs/a cow/a horse
- dogs will attack monsters adjacents to you if you're not between the monsters and them (unleashed behavior)
- they will attack more reliably when there are several of them
- you can move next of hordes of zombies with your pets if they are leashed. If they get stuck, they will try to move "through" the monsters (this translates to hitting them) to get to you 

https://user-images.githubusercontent.com/71428793/195500902-98e14d99-e7d6-47a1-818b-b0f61134e7c8.mp4

### CODE REVIEW

File: src/monattack.cpp [hunk 1]
```diff
@@ -4529,7 +4529,7 @@ bool mattack::longswipe( monster *z )
 static void parrot_common( monster *parrot )
 {
     // It takes a while
-    parrot->moves -= 100;
+    parrot->moves -= 10;
```
Comment (Coolthulhu) [inline src/monattack.cpp:4532]: Looks like an unrelated change sneaked in.

Comment (leoCottret) [reply src/monattack.cpp:4532]: No this is intentionnal, it was part of the problem:
"A dog has a probability to bark at a monster, which remove a whooping 100 move points. This means that given enough monsters, a dog would "bark itself to death", being unable to follow the player even leashed because it used all its move points to bark every turn."
"Reduce the barking cost from 100 to 10. Having your dog unable to move because he's too busy barking at zombies is kind of stupid. And dogs can bark while moving."
"This could buff mi-go (and monsters that use parrot), so I could add a check on leashed monsters/PET/something if needed. But I find it weird that they need to stop attacking/moving to basically just talk."

Comment (Coolthulhu) [reply src/monattack.cpp:4532]: OK, I guess. I'd rather have it not cost any moves then. I'm against tiny costs like this.

Comment (leoCottret) [reply src/monattack.cpp:4532]: I changed it like that in case it would somehow create infinite loops if I completly removed it, but I can remove it and test a bit

Comment (leoCottret) [reply src/monattack.cpp]: I tested with dogs and mi-go, no infinite loops
