### PR TITLE
Revert invstack change and only use the cache when needed

### LINKED ISSUE #1416: Reproducible crash when activating grenades
# Describe the bug

Activating multiple grenades in a row will crash the game.

# Steps To Reproduce

1. Spawn 10 grenades
2. Activate them one by one
3. Crash happens

# Expected behavior

Crashes are obviously unacceptable.

# Screenshots

# Versions and configuration

Reproduces both on Windows releases and git-compiled versions.

# Additional context

Relevant parts of crash log/stacktrace:
```
    ./cataclysm-tiles(_ZNK4item11stacks_withERKS_bb+0x27) [0x1020627]
    ./cataclysm-tiles(_ZN9inventory8add_itemE4itembbb+0x123) [0xfe9143]
    ./cataclysm-tiles(_ZN9inventory7restackER6player+0x344) [0xfea8b4]
    ./cataclysm-tiles() [0xf01e80]
    ./cataclysm-tiles(_ZN10game_menus3inv3useER6avatar+0x1a2) [0xf05d62]
    ./cataclysm-tiles(_ZN13avatar_action8use_itemER6avatarR13item_location+0x50) [0xabd800]
    ./cataclysm-tiles(_ZN13avatar_action8use_itemER6avatar+0x22) [0xabd6c2]
    ./cataclysm-tiles(_ZN4game13handle_actionEv+0x213e) [0xf4424e]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x978) [0xe79ab8]
```

```
    …/src/crash.cpp:110
    ??
    ??:0
    std::__uniq_ptr_impl<relic, std::default_delete<relic> >::_M_ptr() const
    /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:173
    std::unique_ptr<relic, std::default_delete<relic> >::get() const
    /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:422
    std::unique_ptr<relic, std::default_delete<relic> >::operator bool() const
    /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:436
    item::is_relic() const
    …/src/item.cpp:6668
    item::stacks_with(item const&, bool, bool) const
    …/src/item.cpp:878
    inventory::add_item(item, bool, bool, bool)
    …/src/inventory.cpp:343
    inventory::restack(player&)
    …/src/inventory.cpp:437
    inv_internal(player&, inventory_selector_preset const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/game_inventory.cpp:186
```

My suspicion:
In #1386, an item type cache was added, but from what I can tell, it assumes an item will keep its type forever.
`item::convert` changes the type of an item, but doesn't change its location in the inventory, so it might try to do something on an empty list.
For example, line [`inventory.cpp::429`](https://github.com/SaintCirno9/Cataclysm-BN/blob/752d60d985db4f18b75eeb7aba19c9363e6e595b/src/inventory.cpp#L429)
```C++
other = items.erase( other, iter->front().typeId() );
```
If `iter->front().typeId()` doesn't point to a list containing `other`, the return value of `erase` will be `return std::list<std::list<item> >::erase( stack_iter );`.
So `other` probably becomes this new iterator, which seems to be an iterator to a temporary element.
There really, really should be at least a debugmsg for this case.

### PR DESCRIPTION
**Pull request by SaintCirno9**
#### Summary

SUMMARY: [Bugfixes] "Revert invstack change and only use the cache when needed"

#### Purpose of change

The invstack change to add an items type cache in #1386 seems buggy somehow.  Revert!

#### Describe the solution

Revert  invstack change  and only use the cache when the `inventory::add_item` might be called frequently.

#### Describe alternatives you've considered

More cautious check to guarantee the cache to be right.
But, it doesn't appear to be worth the effort and it's difficult to do.

#### Testing

Open the craft menu with numerous items around, and the performance is fine.

#### Additional context

Fix #1416

### CODE REVIEW

File: src/inventory.h [hunk 1]
```diff
@@ -147,6 +119,9 @@ class inventory : public visitable<inventory>
         // returns a reference to the added item
         item &add_item( item newit, bool keep_invlet = false, bool assign_invlet = true,
                         bool should_stack = true );
+        // use item type cache to speed up, remember to run build_items_type_cache() before using it
```
Comment (Coolthulhu) [inline src/inventory.h:122]: Comments like this indicate a code smell. There should be some check whether type cache is built properly, for example a variable called `cache_dirty` in `inventory`. At the very least, it should cause debugmsgs on attempted use while the cache is not built - it should "loudly" announce that there is an error in the code, so that we can fix it as soon as possible.

See `binned_items` hack. It uses `mutable` and so violates `const` (it's considered tolerable for pure caches that are only used as metadata), but this allows it to be rebuilt where needed.
`binned_items` exists only because of the current bad habit of using same class for both player inventory and crafting inventory. Player inventory is "real", while crafting inventory is just a cache. They have different needs - player inventory wants to change, crafting inventory wants to be fast.

Comment (SaintCirno9) [reply src/inventory.h:122]: So how about separating the crafting inventory part from the current inventory class?
Create a new crafting inventory class that inherits from the inventory class.

Comment (SaintCirno9) [reply src/inventory.h:122]: So much work to do that, I give up. 😢😢😢
Thinking about make this method private since it is fast enough to just use it in form_from_map.

Comment (Coolthulhu) [reply src/inventory.h:122]: Without inheritance would be best, but the problem is that a large amount of code expects crafting inventory to be an inventory, so using a new class would require changing a number of things. Could be less work if the new class had identical function names - they could later be changed to something more proper.

Inheritance adds some performance overhead, but it's not significant unless the function is called a lot. Readability and reliability is more important.

For this PR, it's enough that it prints an error message with `debugmsg` if `add_item_by_items_type_cache` is executed on an inventory without the cache built. For example, a `bool` similar to `binned`, set to `false` whenever an item is added and set to `true` whenever the cache is built.
