### PR TITLE
Fix build on linux64

### LINKED ISSUE #665: Build fails on Make/CMake linux64, would like to contribute
I'm using CMake to build and get some errors
`error: ‘numeric_limits’ is not a member of ‘std’` (due to not including `<limits>` in `units.h`, but the proper line is included for Android src)
`error: unused parameter ‘lang_id’ [-Werror=unused-parameter]`

I'm wondering if I'm missing some build options to make my process a 1:1 with how the release is actually built.
However, even with using the officially supported `Make` process, the first error persists.
Using latest branch of `upload`.
So should I PR this build error as well as changes to `CMakeLists.txt` to make it buildable with CMake?

EDIT:
There's a lot of errors due to the setting for clang-tidy `warnings-as-errors: '*'`
Are these "errors" meant to be fixed, or should clang-tidy options be modified?

### PR DESCRIPTION
**Pull request by nanohard**
#### Summary
SUMMARY: Build "Fix errors preventing build"

#### Purpose of change
Main branch failed to build on `linux64` using both `Make` and `CMake` due to several errors from the compiler.
These changes make it so that there are no build errors preventing the build process from completing without changing build options.
Fixes #665

#### Describe the solution
Please see documented commits.

#### Describe alternatives you've considered
Considered changing `-W` flags, but only 2 errors needed to be fixed.

#### Testing
Build process completes with no errors.

### CODE REVIEW

File: src/language.cpp [hunk 1]
```diff
@@ -484,20 +484,6 @@ std::vector<std::string> get_lang_path_substring( const std::string &lang_id )
     return ret;
 }
 
-bool translations_exists_for_lang( const std::string &lang_id )
```
Comment (Coolthulhu) [inline src/language.cpp:487]: Also exists in `language.h`.

Comment (olanti-p) [inline src/language.cpp:487]: This function is used in translation tests in builds with localization enabled (`LOCALIZE` is defined):
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/458e37fa912345fb2514d2e553cd967811f791c6/tests/translations_test.cpp#L90
Rather then outright removing it, try expanding `#if defined(LOCALIZE)`...`#endif` block to cover the whole function.

Comment (Coolthulhu) [reply src/language.cpp:487]: Might also require an `if defined` in the header if the compiler dislikes declared but unimplemented functions.

**Comment by nanohard** [comment]
Noice, putting the entire function in the definition worked out.
Just now learning C++ and didn't notice what I was looking at.

File: src/language.cpp (hunk 1 above)
Comment (nanohard) [reply src/language.cpp:487]: Noice, putting the entire function in the definition worked out.
Just now learning C++ and didn't notice what I was looking at.

Comment (nanohard) [reply src/language.cpp:487]: Resolved via @olanti-p suggestion. Thanks both!

**Comment by nanohard** [comment]
Added one last item, to make nutrition test pass ([!mayfail] tag). This is standard process for WIP code; we know the test fails and that nutrition is broken there.
