### PR TITLE
Fix turrets aiming through walls

### LINKED ISSUE #2431: Hostile turrets attempt to fire at a player (or their car) through walls when piloting a car
### Describe the bug

This is best noticed when driving a car near a military bunker or lab entrance. It could be confused with unseen combat but it's not that. In fact, at a bunker, this behavior can be exploited. If the player has room to pilot the vehicle to the appropriate side of the bunker, it is possible to get 3 of the 6 turrets to fire at the other three. But generally turrets firing without a line of sight is of course just inappropriate turret behavior.

### Steps To Reproduce

1. Teleport or travel to an unvisited military bunker (red "B" on map).
2. As soon as you're in range, the turrets inside will start firing, but only if you're piloting a vehicle.

### Screenshots

_No response_

### Versions and configuration

Win 64bit, game version 0.2 stable, also 2023-03-15-1210

### Additional context

Since firing at a player-piloted vehicle should be a thing even though the player is not seen (due to crouching), there should be checks what's blocking the line of sight. If it's vehicle board or quarterpanel, fire away. If it's a building wall, don't fire. Alternatively, some walls could have some kind of "do not attempt to fire through this wall if you're a turret" tag. And then we would plaster the tag all over on bunker and lab walls on surface level.

### LINKED ISSUE #2578: Turrets began to see through walls.
### Describe the bug

Turrets began to see through bunker walls. If you turn 3D on, they begin to see through the lower floors of the bunkers.

### Steps To Reproduce

1. Approach the military bunker, which has turrets inside. 
2. Hear the firing.
 3. There is no one inside except the turrets.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
- OS Version: 10.0 2009
- Game Version: 45939d4 [64-bit]
- Graphics Version: Tiles
- Game Language: [russian]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joveeater**
#### Summary

SUMMARY: Bugfixes "Fix turrets aiming through walls"

#### Purpose of change

Fixes #2578 fixes #2431

#### Describe the solution

Bit of an overhaul to their targeting to make it a little better at selecting the closest target and a bit clearer. 

#### Describe alternatives you've considered

Just adding the missing vision check.

#### Testing

I had a drive around some turrets and they're firing correctly now.

### CODE REVIEW

**Review by scarf005 — APPROVED** [review]
image
confirmed that turrets do not shoot at vehicles when blocked by walls. (casings are from testing prev. behavior)

wish std::optional were used, but it'd be better to just use ranges-v3 at that point.

**Comment by Firestorm01X2** [comment]
@joveeater For me turret now do not even shoot vehicle. Tested on APC. Save attached:
[turret.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/11186164/turret.zip)

**Comment by metalheimer** [comment]
>  (casings are from testing prev. behavior)

It's not fixed for me. Tried a very recent version (no game mods either). Are you sure those bunker turrets weren't just out of ammo? Bunker turrets still try to pepper me through walls. Tried with a car, and a bicycle. They shoot every time.

**Comment by scarf005** [comment]
hecc. recompile time.

**Comment by scarf005** [comment]
image
@metalheimer that's because this pull request is not yet merged.

File: src/mattack_actors.cpp [hunk 1]
```diff
@@ -481,21 +481,42 @@ int gun_actor::get_max_range()  const
...
         }
-        int new_dist = rl_dist( z.pos(), v.pos );
-        if( v.v->velocity != 0 && new_dist < range ) {
-            chosen = v.v;
-            range = new_dist;
+
+        bool found_controls = false;
+
+        for( const vpart_reference &vp : v.v->get_avail_parts( "CONTROLS" ) ) {
+            if( z.sees( vp.pos() ) ) {
```
Comment (scarf005) [inline src/mattack_actors.cpp:496]: image
image

This line does not account for vehicle parts that obstruct views.
- bicycle test worked because its control was visible from outside.
- @Firestorm01X2's APC test did not work because quarterpanels were blocking the vehicle control from the view of the turret.

**Review by scarf005 — CHANGES_REQUESTED** [review]

**Comment by joveeater** [comment]
I've fixed the APC problem. Good catch. It no longer lets a vehicle block the view to that same vehicle. I also refactored it to use optional, was a good suggestion.

**Review by scarf005 — APPROVED** [review]
|       bicycle       |     APC     |
| :-----------------: | :---------: |
| ![bicycle][bicycle] | ![APC][apc] |

|   turret    | bicycle(stopped) | bicycle(moving) | APC(stopped) | APC(moving) |
| :---------: | :--------------: | :-------------: | :----------: | :---------: |
|   normal    |      shoots      |     shoots      |              |   shoots    |
| behind wall |                  |                 |              |             |

looks like it's working as intended.

[apc]: https://user-images.githubusercontent.com/54838975/230912935-fabcdd47-866a-45bc-a36a-6a7395fbbb9e.png
[bicycle]: https://user-images.githubusercontent.com/54838975/230913818-d47e4c24-cd2f-4631-bd4d-cdd2a5b2ff10.png

**Comment by joveeater** [comment]
Urgh, this still doesn't handle floors correctly atm. I'll take another look.

**Comment by Firestorm01X2** [comment]
> looks like it's working as intended.

I'll double check. No idea why it does no for my save. I've used light turret and apc to test.

**Comment by Firestorm01X2** [comment]
> Urgh, this still doesn't handle floors correctly atm. I'll take another look.

I'll convert it to draft to prevent early merging.

**Comment by scarf005** [comment]
i think using `draft` would be better since it's official github feature.
