### PR TITLE
fix: flotation device doesnt give a swim bonus underwater

### LINKED ISSUE #7095: The Flotation Vest removes the stamina drain of swimming while swimming underwater
### Describe the bug

Wearing the flotation vest allows you to swim underwater, with the same stamina reducing effect, as if you were swimming on the surface with it.

You cannot dive from the surface while wearing the vest (As intended), but you CAN however go deeper if you're already underwater and wearing the vest.

### Steps To Reproduce

1. Do not wear your flotation vest
2. Dive underwater one or more tiles
3. Put on your flotation vest
4. You can now swim without any/minimal stamina drain
5. You can even go up and down in elevation, as long as you're underwater and don't break the surface.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.5624 (23H2)
- Game Version: 6f5490c [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    UDP Redux [udp_redux],
    Pride Flags for BN [pride_flags],
    Tablet e-book [tablet_ebook],
    Change Hairstyle [change_hairstyle],
    Aftershock [aftershock],
    Civilians [civilians],
    Trailer Parks [trailerpark],
    No Wasps [No_Wasps]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AutumnNova**
## Purpose of change (The Why)
fixes #7095 
Diving underwater and then equipping a flotation vest increases your swim speed enough that your stamina does not drop while swimming. 
This is presumably unintended given items with the flotation flag prevent you from diving

## Describe the solution (The How)

Simply disable the swim speed bonus from flotation devices when underwater

## Describe alternatives you've considered
Additionally preventing a player from wearing a flotation vest while underwater
Making the flotation vest drag the player back to the surface somehow?

## Testing

Located the nearest lake and swam to the bottom of it
Wore a flotation vest and swam around to confirm stamina depleted normally

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/contribute/changelog_guidelines/).
- [ ] I ran the [code formatter](https://docs.cataclysmbn.org/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -1118,7 +1118,7 @@ int Character::swim_speed() const
 
     /** @EFFECT_DEX increases swim speed */
     ret -= str_cur * 6 + dex_cur * 4;
-    if( worn_with_flag( flag_FLOTATION ) ) {
+    if( worn_with_flag( flag_FLOTATION ) && !is_underwater() ) {
```
Comment (chaosvolt) [inline src/character.cpp]: One issue with this is it may undermine putting a life jacket on while drowning on the surface, since that counts as underwater. I've checked out the branch and about to test a fix that'll check specifically if the wearer's in a water cube tile.

**Review by chaosvolt — COMMENTED** [review]
Lemme know how these look to you. Testing so far and:
1. Compiled and load-tested.
2. Tested putting on a life jacket while drowning on the surface, it still correctly stops me from drowning.
3. Teleport under the surface, I'm now drowning again.
4. Try taking it off, can no longer put it back on until I'm on the surface again.
5. Confirmed that if I warp down underwater while wearing a flotation vest I still drown.

**Comment by AutumnNova** [comment]
Ah, I did forget about checking if it all still worked when drowning, whoops
Thanks for spotting and fixing that

**Review by chaosvolt — APPROVED** [review]
One minor thing I might look at when I get home for a future PR, putting on a life jacket when drowning under the surface still requires you to surface manually, so I might also try to figure out how to make it force the player to the surface if they get under the surface with one on. Only matters in cases like stepping out the airlock of the underwater research lab if I recall.
