### PR TITLE
fix: Digestion Bionic now prevents food poisoning from water

### LINKED ISSUE #6524: Drinking dirty water with the Expanded Digestive System bionic installed still gives you food poisioning
### Describe the bug

The Expanded Digestive System bionic should prevent all instances of food poisoning. However, when drinking dirty water (i.e. from a toilet), the player still gets food poisoning even with the bionic installed.

### Steps To Reproduce

1. Start a new character on a fresh world.
2. Use the debug menu to install the Expanded Digestive System bionic.
3. Use the debug menu to increase the character's thirst need to the point where they are thirsty.
4. Find the nearest toilet and consume the water from it (possibly multiple times, unsure if that particular water is a 100% chance)
5. Check the character status window. The character will be food poisoned.

### Screenshots

Image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5737 (22H2)
- Game Version: 9436da0 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    UDP Redux [udp_redux]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yizow**
## Purpose of change (The Why)

Drinking dirty water with a Digestive CBM should prevent food poisoning.

closes #6524

## Describe the solution (The How)

Add a check to `Character::eat()` for `bio_digestion` bionic when consuming poison.
Currently, we only do this check for spoilage.

* Factors out a `consume_poison` function to start chipping away at the monster `eat`

## Describe alternatives you've considered

Waterborne E. Coli for everybody.

## Testing

Add tests for consuming poison and various forms of poison immunity.

In test world:
use debug menu and drink some toilet water with and without digestive cbm.

* validate that you only get food poisoning without it installed. 
* validate that unclean pop-up only happens without it installed
### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.

### CODE REVIEW

**Review by scarf005 — CHANGES_REQUESTED** [review]
image

CBM shouldn't prompt user on unclean water too

File: tests/consumption_test.cpp [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+// manipulating RNG and I don't want to figure that out yet.
+TEST_CASE( "consume_poison", "[consumption]" )
+{
+    item test_poison{};
+    avatar test_consumer{};
+
+    SECTION( "not poison" ) {
+        test_poison.poison = 0;
+        consume_poison( test_consumer, test_poison );
+        effect &is_poisoned = test_consumer.get_effect( effect_foodpoison );
```
Comment (OrenAudeles) [inline tests/consumption_test.cpp:28]: You are getting a reference and aren't changing anything about the stored effect. This should be

```suggestion
        const effect &is_poisoned = test_consumer.get_effect( effect_foodpoison );
```

File: tests/consumption_test.cpp [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+        CHECK( !is_poisoned );
+    }
+
+    SECTION( "is poison" ) {
+        test_poison.poison = 10;
+
+        SECTION( "vulnerable" ) {
+            consume_poison( test_consumer, test_poison );
+
+            effect &is_poisoned = test_consumer.get_effect( effect_foodpoison );
```
Comment (OrenAudeles) [inline tests/consumption_test.cpp:39]: Since you just want to know if the returned effect is valid while not changing anything about the effect it would be better to use
```suggestion
            bool is_poisoned = static_cast<bool>( test_consumer.get_effect( effect_foodpoison ) );
```

File: tests/consumption_test.cpp [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+            CHECK( is_poisoned );
+        }
+
+        SECTION( "immune" ) {
+            SECTION( "POISRESIST trait" ) {
+                test_consumer.set_mutation( trait_POISRESIST );
+                consume_poison( test_consumer, test_poison );
+
+                effect &is_poisoned = test_consumer.get_effect( effect_foodpoison );
```
Comment (OrenAudeles) [inline tests/consumption_test.cpp:48]: Same as above

File: tests/consumption_test.cpp [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+                CHECK( !is_poisoned );
+            }
+
+            SECTION( "EATDEAD trait" ) {
+                test_consumer.set_mutation( trait_EATDEAD );
+                consume_poison( test_consumer, test_poison );
+
+                effect &is_poisoned = test_consumer.get_effect( effect_foodpoison );
```
Comment (OrenAudeles) [inline tests/consumption_test.cpp:56]: Same as above

File: tests/consumption_test.cpp [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+                CHECK( !is_poisoned );
+            }
+
+            SECTION( "bio_digestion bionic" ) {
+                test_consumer.add_bionic( bio_digestion );
+                consume_poison( test_consumer, test_poison );
+
+                effect &is_poisoned = test_consumer.get_effect( effect_foodpoison );
```
Comment (OrenAudeles) [inline tests/consumption_test.cpp:64]: Same as above

**Review by OrenAudeles — DISMISSED** [review]
Nice, compact PR. In the tests you aren't modifying the `effect&` returned by `get_effect` so there's no reason to ever keep it around. Convert to `bool` explicitly instead of implicitly as part of the `CHECK( ... )`

**Review by scarf005 — APPROVED** [review]
image image

10/10 would drink from toilet again
