### PR TITLE
fix: impossible hibernation

### LINKED ISSUE #2010: Impossible to hibernate
### Describe the bug

It seems that the activable hibernation can't hibernate.
I couldn't trigger it on DDA too.
In any case, if there's a way to trigger it, being at maximum calories level should allow you to hibernate.

### Steps To Reproduce

1. Make a player with the hibernation mutation
2. Set your calories to maximum, continue eating
3. Activate the mutation
4. Go to sleep. No "You enter hibernation" message

### Expected behavior

The mutation should be usable

### Screenshots

_No response_

### Versions and configuration

- Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoCottret**
#### Summary
SUMMARY: Bugfixes "Fix impossible hibernation"

Fixes #2010

#### Purpose of change
1) Hibernation could only be triggered with an obscure system taking into account the possible calories you could burn in a day. Even if it could be triggered, the mechanic wasn't clear enough for the average player

#### Describe the solution
- now you can hibernate when you're above 90% of maximum stored calories, it's just as simple as that
- it was also impossible to hibernate since your character would wake up after your fatigue level reached 0. I added an extra condition to ignore the fatigue level
- also, the rate of hunger was divided by 7 when hibernating, but it did close to nothing. I even tried to reduce it by 100000, this didn't change a thing. So I used a system to compensate the lost calories, taking into account the metabolic rate of the player

#### Describe alternatives you've considered
- fixing the bug that makes hunger rate modifications ignored (instead of my 3rd change in Describe the solution)

#### Testing
- Tested with light eater, fast metabolism, very fast metabolism, high thirst
- Being either too thirsty or hungry will wake you up
- With very fast metabolism, you can almost go through the 7 days of hibernations, from 17500 to ~8000 calories

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -4929,8 +4929,11 @@ needs_rates Character::calc_needs_rates() const
         rates.recovery = 2.0f * ( 1.0f + mutation_value( fatigue_regen_modifier ) );
         if( is_hibernating() ) {
             // Hunger and thirst advance *much* more slowly whilst we hibernate.
-            rates.hunger *= ( 1.0f / 7.0f );
-            rates.thirst *= ( 1.0f / 7.0f );
+            // This will slow calories consumption enough to go through the 7 days of hibernation
+            if( one_in( 50 / rates.hunger ) ) {
+                g->u.mod_stored_kcal( 1 );
```
Comment (Coolthulhu) [inline src/character.cpp:4934]: Referencing global `g->u` here is wrong. If NPCs could hibernate, this would make them "feed" the player with their good vibes.

**Comment by Coolthulhu** [comment]
> the rate of hunger was divided by 7 when hibernating, but it did close to nothing. I even tried to reduce it by 100000, this didn't change a thing. So I used a system to compensate the lost calories, taking into account the metabolic rate of the player

That would suggest something is not working right. This needs to be tested and either fixed or at least made known.

File: src/character.cpp (hunk 1 above)
Comment (leoCottret) [reply src/character.cpp:4934]: I think I fixed it with get_player_character(), I can't compile it anymore since it's an old version

**Comment by leoCottret** [comment]
> 

I suppose it's due to a rounding to 1 (probably from the function that updates the stomach).

File: src/character.cpp [hunk 2]
```diff
@@ -4929,8 +4929,11 @@ needs_rates Character::calc_needs_rates() const
         rates.recovery = 2.0f * ( 1.0f + mutation_value( fatigue_regen_modifier ) );
         if( is_hibernating() ) {
             // Hunger and thirst advance *much* more slowly whilst we hibernate.
-            rates.hunger *= ( 1.0f / 7.0f );
-            rates.thirst *= ( 1.0f / 7.0f );
+            // This will slow calories consumption enough to go through the 7 days of hibernation
+            if( one_in( 50 / rates.hunger ) ) {
+                get_player_character().mod_stored_kcal( 1 );
```
Comment (olanti-p) [inline src/character.cpp:4934]: It still references the `g->u`, `get_player_character()` is just a modern alias for it.

Look at this function's signature, `needs_rates Character::calc_needs_rates() const`.
 
It's a function that
1. Belongs to `Character` class, meaning it runs for some specific `Character` instance, available through pointer `this`. It may be the `g->u`, or it may be one of the NPCs, as both NPCs and player's avatar are `Character`s.
2. Is a `const` function, meaning it should only check or calculate some value without modifying the `Character` instance it belongs to (which its name also implies). If, for example, someone were to add a sidebar panel that displays character's need rates, this function would get called twice (for character update + for drawing the panel), so the character would magically gain double the amount of calories.

This calorie modification should be done wherever the code applies these needs.

**Comment by scarf005** [comment]
## Testing

Cataclysm: Bright Nights - f8ca9882cb0e_01

Cataclysm: Bright Nights - f8ca9882cb0e_02

1. changed time to day 0, 00:00:00.
2. added bear trait
3. resetted all basic needs.
4. slept.
5. was able to hibernate ~7 days.

## Describe Changes

turns out `kcal_per_time` did not take account of `rates.hunger` because it used `Character::bmr()`. at first naively tried `kcal_per_time * rates.hunger` but it didn't work because it squared `metabolic_rate_base`.

```
kcal_per_time 
= bmr() * N
= metabolic_rate_base() * N

rates.hunger
= calc_needs_rates()
= metabolic_rate() * N
= metabolic_rate_base()

therefore, kcal_per_time * rates.hunger = metabolic_rate_base() ^ 2 * N
```

extracted value into `metabolic_base_kcals` and multiplied it instead.

## Alternatives

buff hibernation metabolic rate further from current `2` to `2.x`?

**Review by chaosvolt — APPROVED** [review]
The missile is eepy
