### PR TITLE
fix: reloading magazine properly shows non-empty magazines with different, but compatible ammo

### LINKED ISSUE #5594: The 1911-460 pistol cannot be reloaded with magazines that have ammo in them
### Describe the bug

The 1911-460 pistol is a 1911 customized to fire .460 Rowland ammunition. It is actually the only gun in the game that fires .460 Rowland. It is compatible with both .460 and the common .45, and uses ordinary 1911 magazines which themselves are also compatible with both .460 and .45. 
However, it can only be reloaded with those magazines if they are empty. It will not accept magazines with _either_ .460 or .45 ammo in them, only empty magazines. Once the gun has an empty magazine, it can then be loaded with either .460 Rowland or .45, and they can even be fired from it.

It doesn't seem to be a simple ammo compatibility issue. The gun accepts the bullets and it accepts the mags, just not both at the same time.

### Steps To Reproduce

1. get a 1911-460 (not a regular 1911)
2. get a 1911 magazine with ammo
3. attempt to reload 1911-460
4. you can't
5. unload the 1911 magazine
6. attempt to reload 1911-460
7. now it works
8. attempt to reload 1911-460 again (with the empty mag inside)
9. also works

### Screenshots

cata-2024-10-21-15-24-02

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro N
- Game Version: ee91baf4dd8 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Item Category Overhaul [Item_Category_Overhaul],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp]
]

### Additional context

_No response_

### LINKED ISSUE #5623: Guns must be loaded with an empty magazine that accepts both ammo types to switch ammo types
### Describe the bug

When defining two calibers such as 5.56 and .300 blackout, or in my case two variants of 5.56 which are unique and separate, you need to load an empty magazine compatible with both to switch from one type to another. Examples are in screenshots.

### Steps To Reproduce

1. Have an M4A1 or carbon fiber assault rifle set to 5.56 NATO with a full magazine of 5.56 NATO
2. Attempt to switch to a full magazine of .300 Blackout
3. You can't. Now try an empty magazine in your gun and loose ammo. You can. This flips it to .300 Blackout and causes the inverse, you can't reload with 5.56 now unless you've inserted a fully empty magazine which accepts 5.56 AND blackout.

### Screenshots

image
image
image
image

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Bazzite; Description: Bazzite 40 (FROM Fedora Kinoite); Release: 40; Codename: Holographic; 
- Game Version: bca5ab3 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water],
    No Filthy Clothing [no_filthy_clothing],
    No Wasps [No_Wasps],
    Fox's Revisions mod [FoxRevisions],
    MSX Fake Snow [UDP_BN_FAKE_SNOW],
    Item Category Overhaul [Item_Category_Overhaul],
    Prevent Zombie Revivication [no_reviving_zombies],
    Prevent Zombification [no_zombify],
    Deadlier Zombies [Deadly_Zeds],
    No Mutant Meat [NoMutantMeat]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by usagirei**
## Purpose of change (The Why)

- Resolves #5623 
- Resolves #5594

## Describe the solution (The How)

Magazine selection logic had a minor iteration oversight:
Instead of considering accepting a non-empty magazine if the contained ammunition matched ***any*** of the supported ammo types, the magazine was rejected it if it didn't match ***all*** of them,

## Describe alternatives you've considered

Insert empty magazines in the weapon and magic-reload the rounds inside it without taking the magazine out.

## Testing

Vanilla:
* Loaded game, spawned 1911-460, and 3 mags, one empty, one with 460 and one with 45
* Reloading works as expected with any given combination

Modded:
* Tested with Modern Weapon Pack Extended SCAR-H, works as expected too.

## Additional context

image

image

### Mandatory

- [x] I wrote the PR title in [conventional commit format](https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/).
- [x] I ran the [code formatter](https://docs.cataclysmbn.org/en/contribute/contributing/#code-style).
- [x] I linked any relevant issues using [github keyword syntax](https://docs.cataclysmbn.org/en/contribute/contributing/#pull-request-notes) like `closes #1234` in [Summary of the PR](#purpose-of-change-the-why) so it can be closed automatically.
- [x] I've [committed my changes to new branch that isn't `main`](https://docs.cataclysmbn.org/en/contribute/contributing/#make-your-changes) so it won't cause conflict when updating `main` branch later.
- [x] I understand that, unless specified otherwise, [my contributions will fall under the AGPL v3.0 and/or CC-BY-SA 4.0 licenses](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/LICENSE.txt)

### CODE REVIEW

File: src/character_functions.cpp [hunk 1]
```diff
@@ -1177,11 +1177,16 @@ void find_ammo_helper( T &src, const item &obj, bool empty, Output out, bool nes
...
-                        if( node->contents.front().ammo_type() != at ) {
-                            return VisitResponse::SKIP;
+                        if( node->contents.front().ammo_type() == at ) {
+                            match = true;
+                            break;
                         }
                     }
+                    if( !match ) {
+                        return VisitResponse::SKIP;
+                    }
```
Comment (scarf005) [inline src/character_functions.cpp:1189]:
```suggestion
                    const bool match = std::ranges::any_of( ammo, [&]( const ammotype & at ) {
                        return node->contents.front().ammo_type() == at;
                    } );
                    if( !match ) return VisitResponse::SKIP;
```
maybe we could use [std::ranges::any_of](https://en.cppreference.com/w/cpp/algorithm/ranges/all_any_none_of) here

**Review by scarf005 — DISMISSED** [review]
image

1. spawned 1911-460, 3 m1911 magazines
2. unloaded two, loaded one with .460 Rowlands
3. attempted to reload 1911-460
4. confirmed i could reload 3 magazines 

seems to work on my machine.

File: src/character_functions.cpp (hunk 1 above)
Comment (usagirei) [reply src/character_functions.cpp]: Resylt should be the same, if a bit cleaner.
Tested on my end with both vanilla and modded again, still works as intended.
